# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180906_0915'),
        ('polls', '0004_add-polls-permissions-to-groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SiteLanguage'),
        ),
        migrations.AddField(
            model_name='choice',
            name='translated_pages',
            field=models.ManyToManyField(blank=True, related_name='_choice_translated_pages_+', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SiteLanguage'),
        ),
        migrations.AddField(
            model_name='question',
            name='translated_pages',
            field=models.ManyToManyField(blank=True, related_name='_question_translated_pages_+', to='polls.Question'),
        ),
    ]
